import { Comfortaa } from 'next/font/google';
import './globals.css';
import Navbar from './components/NavBar';

const comfortaa = Comfortaa({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body
				className={`${comfortaa.className} min-h-screen bg-gradient-radial from-gray-100 to-gray-200`}
			>
				<Navbar />
				<main className="container px-4 py-8 mx-auto">
					{children}
				</main>
			</body>
		</html>
	);
}
